# Generated by Django 3.2.7 on 2021-09-06 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shrinker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='shorturl',
            name='long_url',
            field=models.URLField(),
        ),
    ]
